import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "@/app/_styles/globals.css";

const poppins = Poppins({
    subsets: ["latin"],
    display: "auto",
    weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
    title: "Tinkin ONG Recipe",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={`${poppins.className} antialiased`}>{children}</body>
        </html>
    );
}
